$(document).ready(function(){
    $("#colm1").click(function(){
      $(".port1").toggle();
    });
  });
  $(document).ready(function(){
    $("#colm2").click(function(){
      $(".port2").toggle();
    });
  });