$(document).ready(function(){
    $("#colm1").click(function(){
      $(".port1").toggle();
    });
  });
  $(document).ready(function(){
    $("#colm2").click(function(){
      $(".port2").toggle();
    });
  });
  $(document).ready(function(){
    $("#colm3").click(function(){
      $(".port3").toggle();
    });
  });
  $(document).ready(function(){
    $("#hover1").mouseover(function(){
      $(".hid1").show();
    });
    $("#hover1").mouseout(function(){
      $(".hid1").hide();
    });
  });
  $(document).ready(function(){
    $("#hover2").mouseover(function(){
      $(".hid2").show();
    });
    $("#hover2").mouseout(function(){
      $(".hid2").hide();
    });
  });
  $(document).ready(function(){
    $("#hover3").mouseover(function(){
      $(".hid3").show();
    });
    $("#hover3").mouseout(function(){
      $(".hid3").hide();
    });
  });
  